#ifndef SIMULATIONCORE_GLOBAL_H
#define SIMULATIONCORE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SIMULATION_CORE_LIBRARY)
#  define SIMULATION_CORE_SHARED_EXPORT Q_DECL_EXPORT
#else
#  define SIMULATION_CORE_SHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // SIMULATIONCORE_GLOBAL_H
